### ISSUE TITLE
hubicfuse hangs on start

### ISSUE THREAD

**Issue by artursmolarek** [TurboGit/hubicfuse#44]
Configure/make without any problems. Token also was generated succesfully (I see my app in apps connected to my hubic account).

But when I type:

> hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other

then nothing is happening (any output to stdin).

I checked also (when process is running):

> mount | grep hubic

but there are no results.

Any hints?

My system is Debian Wheezy.

**Comment by TurboGit** [comment]
And if you run hubicfuse with debug trace, what is the output:

> hubicfuse /mnt/hubic -d -o noauto_cache,sync_read,allow_other

**Comment by artursmolarek** [comment]
> !!! Authenticating... (client_id = 'api_hubic_XXX')

**Comment by TurboGit** [comment]
Hum! Hanging very early then. I'm using Debian sid/unstable maybe the issue. You have libjson 0.10 right? Maybe the issue. Do you have another machine with a more recent version of GNU/Debian to try?

**Comment by artursmolarek** [comment]
The same situation on Ubuntu 14.04.

libjson0 version:

> Version: 0.11-3ubuntu1.2

**Comment by TurboGit** [comment]
Permissions issues? Have you tried to mount with sudo? BTW, which version are you using? The latest Git?

**Comment by TurboGit** [comment]
What is displayed with:

> ls -al /mnt/hubic/

**Comment by artursmolarek** [comment]
I tried as root, so this are not privileges issues. I am using latest version from repo.

> root@as1:~# ls -al /mnt/hubic/
> total 8
> drwxr-xr-x 2 root root 4096 Feb  7 15:11 .
> drwxr-xr-x 3 root root 4096 Feb  7 15:11 ..

**Comment by TurboGit** [comment]
Ok, so we are using the same HubiC version and I have the same permissions on /mnt/hubic... Since it is working on Ubuntu 14.10 that's probably an issue with an old library (fuse? json? curl?).

**Comment by artursmolarek** [comment]
Probably you are right.
This are versions from not working Ubuntu (14.04):

> Package: libfuse2
> Version: 2.9.2-4ubuntu4

> Package: curl
> Version: 7.35.0-1ubuntu2.2

> Package: libjson0
> Version: 0.11-3ubuntu1.2

Please let me know if you need more details.

**Comment by TurboGit** [comment]
Has this been working on this machine before?

If an update of fuse has been made on the machine you need to clean up and rebuilt hubicfuse:

> $ make clean
> $ make

I remember one people having this hang at start and it was solved this way.

**Comment by artursmolarek** [comment]
No, this wasn't working before. I tried as you suggested: 

> make clean
> make

Still the same problem.

**Comment by TurboGit** [comment]
My versions, pretty close to what you have:

libjson0:
  Installed: 0.11-4

libcurl3:
  Installed: 7.38.0-4

libfuse2:
  Installed: 2.9.3-15+b1

No more idea at this stage, sorry. You'll need to debug this a bit on your side.

**Comment by gregfr** [comment]
I have the same problem, did you find a solution?

**Comment by gregfr** [comment]
I'm not a C developer, so forgive me if I say something stupid. I tried "strace" and got a lot of:

recvfrom(4, 0x7876c0, 5, 0, 0, 0)       = -1 EAGAIN (Resource temporarily unavailable)

does it help?

**Comment by TurboGit** [comment]
It does not help even though it would indeed be the issue. But I cannot guess what is file-descriptor 4, but it seems that it has trouble reading from it.

Don't you have a kind of firewall? Maybe that's the issue. Just a test, can you run this:

$ wget http://google.com

and

$ wget https://google.com

What's the output?

**Comment by artursmolarek** [comment]
Seems that issue can be marked as solved.
At the moment there is no problem with mount under Debian Wheezy.

@gregfr - could you please confirm it?

**Comment by TurboGit** [comment]
Ok, closing then. Thanks for the feedback.
